name: conda_qres_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.26.2
  - torch=2.2.1
  - geopandas
  - networkx
  - overpy
  - osmnx
  - jupyter
  - notebook=7.1.2
  - geopy
  - openmatrix
  - pyyaml=6.0.1
  - gymnasium=0.29.1
  - rliable=1.0.8
  - ruamel.yaml=0.18.6
  - pip
  - pip:
      - wandb
